### ISSUE TITLE
[feat] 하루다짐, 회고일기, 짧은독서 back버튼 통한 뷰 연결 

### ISSUE THREAD

**Issue by minseungseon** [nneaning/meaning_iOS#28]
## CHALLENGE 내용 
- [ ] 각각 뷰에서 백 버튼을 그 이전 뷰로 연결 할 예정입니다!

## 관련 스크린샷 
![image.png](https://images.zenhubusercontent.com/5feb2a148d2c7606c60ae6a8/60dc06b6-3fe0-4742-8f05-d5cb9b021155)

## 관련된 이슈
그동안 2nd/card_detail epic 에 쌓인 모든 이슈와 관련이 있습니다~

## 논의했던 관련 레퍼런스
x

## 유의할 점
@xwoud 
기상인증 뷰가 혹시 나왔나요?! 일단 기상인증 은 저한테 연결할 게 없으니 기상인증 <-- 하루다짐 연결이 가능한지 알려주시면 좋겠습니다! :heart:

**Comment by xwoud** [comment]
기상인증을 제외하고는 모두 back 버튼이 home뷰로 돌아가게 하는 역할이고 기상인증도 아마 navigation controller로 연결될 예정이라서 모두 navigation pop 코드 달아주시면 될꺼같아요!
